name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "flask-application-packages-10082020"
  EB_APPLICATION_NAME       : "MyFlask"
  EB_ENVIRONMENT_NAME       : "Myflask-env-1"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-central-1"  
  
on:
  push:
    branches: [ master ]

jobs:
  my-ci-part:
    runs-on: ubuntu-latest
    steps:
    - name: Git clone our repo
      uses: actions/checkout@v1
    
    - name: Create zip deployment package
      run: zip r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *-git*
    
#  my-cd-part:
#    runs-on: ubuntu-latest
